### PR TITLE
Fix compatibility with Node.js >= 12.9.0

### PR DESCRIPTION
**Pull request by lpinca**
The symbol description has been changed in https://github.com/nodejs/node/commit/d30354859c.

cc: @3rd-Eden

### CODE REVIEW

**Comment by alimvedats** [comment]
I've been investigating this problem for two days, you sent it before me 👍

**Comment by lpinca** [comment]
@3rd-Eden ping

**Comment by Bajix** [comment]
@3rd-Eden Can you merge this and release? This issue's bound to result in troves of engineers going down the debugging rabbit hole. This presented for me as an intermittent failure that would sometimes cause my tests to fail, but with no consistency, making it somewhat of a head scratcher. I ended up downgrading to NodeJS 12.8.1 as a stop gap measure, but now this is blocking me from upgrading to 12.10.0.

**Comment by 3rd-Eden** [comment]
Merged, published as 1.0.2. Sorry for the inconvenience caused.

**Comment by Bajix** [comment]
Thanks for handling this! You're an open source rock star!

**Pull request merged**
